//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Microsoft.Extensions.Localization;
using Envelope.Extensions;
using Envelope.Localization;

namespace Envelope.Validation;

public partial class Resources
{
	public partial class Validation
	{
		public static class __Keys
		{

			public const string DefaultOrEmpty = "DefaultOrEmpty";

			public const string DefaultOrEmpty_WithProperty = "DefaultOrEmpty_WithProperty";
			public const string DefaultOrEmpty_WithProperty_p_PropertyName = "PropertyName";

			public const string Email = "Email";

			public const string Email_WithProperty = "Email_WithProperty";
			public const string Email_WithProperty_p_PropertyName = "PropertyName";

			public const string Equal = "Equal";
			public const string Equal_p_ValueToCompare = "ValueToCompare";

			public const string Equal_WithProperty = "Equal_WithProperty";
			public const string Equal_WithProperty_p_PropertyName = "PropertyName";
			public const string Equal_WithProperty_p_ValueToCompare = "ValueToCompare";

			public const string ExactLength = "ExactLength";
			public const string ExactLength_p_Length = "Length";

			public const string ExactLength_WithProperty = "ExactLength_WithProperty";
			public const string ExactLength_WithProperty_p_Length = "Length";
			public const string ExactLength_WithProperty_p_PropertyName = "PropertyName";

			public const string ExclusiveBetween = "ExclusiveBetween";
			public const string ExclusiveBetween_p_From = "From";
			public const string ExclusiveBetween_p_To = "To";

			public const string ExclusiveBetween_WithProperty = "ExclusiveBetween_WithProperty";
			public const string ExclusiveBetween_WithProperty_p_From = "From";
			public const string ExclusiveBetween_WithProperty_p_PropertyName = "PropertyName";
			public const string ExclusiveBetween_WithProperty_p_To = "To";

			public const string ExclusiveInclusiveBetween = "ExclusiveInclusiveBetween";
			public const string ExclusiveInclusiveBetween_p_From = "From";
			public const string ExclusiveInclusiveBetween_p_To = "To";

			public const string ExclusiveInclusiveBetween_WithProperty = "ExclusiveInclusiveBetween_WithProperty";
			public const string ExclusiveInclusiveBetween_WithProperty_p_From = "From";
			public const string ExclusiveInclusiveBetween_WithProperty_p_PropertyName = "PropertyName";
			public const string ExclusiveInclusiveBetween_WithProperty_p_To = "To";

			public const string GreaterThan = "GreaterThan";
			public const string GreaterThan_p_ValueToCompare = "ValueToCompare";

			public const string GreaterThan_WithProperty = "GreaterThan_WithProperty";
			public const string GreaterThan_WithProperty_p_PropertyName = "PropertyName";
			public const string GreaterThan_WithProperty_p_ValueToCompare = "ValueToCompare";

			public const string GreaterThanOrEqual = "GreaterThanOrEqual";
			public const string GreaterThanOrEqual_p_ValueToCompare = "ValueToCompare";

			public const string GreaterThanOrEqual_WithProperty = "GreaterThanOrEqual_WithProperty";
			public const string GreaterThanOrEqual_WithProperty_p_PropertyName = "PropertyName";
			public const string GreaterThanOrEqual_WithProperty_p_ValueToCompare = "ValueToCompare";

			public const string InclusiveBetween = "InclusiveBetween";
			public const string InclusiveBetween_p_From = "From";
			public const string InclusiveBetween_p_To = "To";

			public const string InclusiveBetween_WithProperty = "InclusiveBetween_WithProperty";
			public const string InclusiveBetween_WithProperty_p_From = "From";
			public const string InclusiveBetween_WithProperty_p_PropertyName = "PropertyName";
			public const string InclusiveBetween_WithProperty_p_To = "To";

			public const string InclusiveExclusiveBetween = "InclusiveExclusiveBetween";
			public const string InclusiveExclusiveBetween_p_From = "From";
			public const string InclusiveExclusiveBetween_p_To = "To";

			public const string InclusiveExclusiveBetween_WithProperty = "InclusiveExclusiveBetween_WithProperty";
			public const string InclusiveExclusiveBetween_WithProperty_p_From = "From";
			public const string InclusiveExclusiveBetween_WithProperty_p_PropertyName = "PropertyName";
			public const string InclusiveExclusiveBetween_WithProperty_p_To = "To";

			public const string Length = "Length";
			public const string Length_p_MaxLength = "MaxLength";
			public const string Length_p_MinLength = "MinLength";

			public const string Length_WithProperty = "Length_WithProperty";
			public const string Length_WithProperty_p_MaxLength = "MaxLength";
			public const string Length_WithProperty_p_MinLength = "MinLength";
			public const string Length_WithProperty_p_PropertyName = "PropertyName";

			public const string LessThan = "LessThan";
			public const string LessThan_p_ValueToCompare = "ValueToCompare";

			public const string LessThan_WithProperty = "LessThan_WithProperty";
			public const string LessThan_WithProperty_p_PropertyName = "PropertyName";
			public const string LessThan_WithProperty_p_ValueToCompare = "ValueToCompare";

			public const string LessThanOrEqual = "LessThanOrEqual";
			public const string LessThanOrEqual_p_ValueToCompare = "ValueToCompare";

			public const string LessThanOrEqual_WithProperty = "LessThanOrEqual_WithProperty";
			public const string LessThanOrEqual_WithProperty_p_PropertyName = "PropertyName";
			public const string LessThanOrEqual_WithProperty_p_ValueToCompare = "ValueToCompare";

			public const string MultiEqual = "MultiEqual";
			public const string MultiEqual_p_ValuesToCompare = "ValuesToCompare";

			public const string MultiEqual_WithProperty = "MultiEqual_WithProperty";
			public const string MultiEqual_WithProperty_p_PropertyName = "PropertyName";
			public const string MultiEqual_WithProperty_p_ValuesToCompare = "ValuesToCompare";

			public const string MultiExclusiveBetween = "MultiExclusiveBetween";
			public const string MultiExclusiveBetween_p_From = "From";
			public const string MultiExclusiveBetween_p_To = "To";
			public const string MultiExclusiveBetween_p_Value = "Value";

			public const string MultiExclusiveBetween_WithProperty = "MultiExclusiveBetween_WithProperty";
			public const string MultiExclusiveBetween_WithProperty_p_From = "From";
			public const string MultiExclusiveBetween_WithProperty_p_PropertyName = "PropertyName";
			public const string MultiExclusiveBetween_WithProperty_p_To = "To";
			public const string MultiExclusiveBetween_WithProperty_p_Value = "Value";

			public const string MultiInclusiveBetween = "MultiInclusiveBetween";
			public const string MultiInclusiveBetween_p_From = "From";
			public const string MultiInclusiveBetween_p_To = "To";
			public const string MultiInclusiveBetween_p_Value = "Value";

			public const string MultiInclusiveBetween_WithProperty = "MultiInclusiveBetween_WithProperty";
			public const string MultiInclusiveBetween_WithProperty_p_From = "From";
			public const string MultiInclusiveBetween_WithProperty_p_PropertyName = "PropertyName";
			public const string MultiInclusiveBetween_WithProperty_p_To = "To";
			public const string MultiInclusiveBetween_WithProperty_p_Value = "Value";

			public const string MultiNotEqual = "MultiNotEqual";
			public const string MultiNotEqual_p_ValuesToCompare = "ValuesToCompare";

			public const string MultiNotEqual_WithProperty = "MultiNotEqual_WithProperty";
			public const string MultiNotEqual_WithProperty_p_PropertyName = "PropertyName";
			public const string MultiNotEqual_WithProperty_p_ValuesToCompare = "ValuesToCompare";

			public const string NotDefaultOrEmpty = "NotDefaultOrEmpty";

			public const string NotDefaultOrEmpty_WithProperty = "NotDefaultOrEmpty_WithProperty";
			public const string NotDefaultOrEmpty_WithProperty_p_PropertyName = "PropertyName";

			public const string NotEqual = "NotEqual";
			public const string NotEqual_p_ValueToCompare = "ValueToCompare";

			public const string NotEqual_WithProperty = "NotEqual_WithProperty";
			public const string NotEqual_WithProperty_p_PropertyName = "PropertyName";
			public const string NotEqual_WithProperty_p_ValueToCompare = "ValueToCompare";

			public const string NotNull = "NotNull";

			public const string NotNull_WithProperty = "NotNull_WithProperty";
			public const string NotNull_WithProperty_p_PropertyName = "PropertyName";

			public const string Null = "Null";

			public const string Null_WithProperty = "Null_WithProperty";
			public const string Null_WithProperty_p_PropertyName = "PropertyName";

			public const string PrecisionScale = "PrecisionScale";
			public const string PrecisionScale_p_ExpectedPrecision = "ExpectedPrecision";
			public const string PrecisionScale_p_ExpectedScale = "ExpectedScale";

			public const string PrecisionScale_WithProperty = "PrecisionScale_WithProperty";
			public const string PrecisionScale_WithProperty_p_ExpectedPrecision = "ExpectedPrecision";
			public const string PrecisionScale_WithProperty_p_ExpectedScale = "ExpectedScale";
			public const string PrecisionScale_WithProperty_p_PropertyName = "PropertyName";

			public const string RegEx = "RegEx";

			public const string RegEx_WithProperty = "RegEx_WithProperty";
			public const string RegEx_WithProperty_p_PropertyName = "PropertyName";
		}
	}
}
